# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2020 Wang Nan <pi3orama@163.com>

# Example makefile in kernel subdir

obj-y += main.o
obj-$(CONFIG_CC_OPTIMIZE_O0) += opt0.o
obj-$(CONFIG_CC_OPTIMIZE_O1) += opt1.o
obj-$(CONFIG_CC_OPTIMIZE_O2) += opt2.o
